// <auto-generated />
namespace LabSem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbcontext));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:LabSem3/Migrations/202206281328030_Context.Designer.cs
            get { return "202206281328030_Context"; }
=======
            get { return "202206281930539_dbcontext"; }
>>>>>>> b840dcb049ecbb332f383bb4ea50b6b78812750c:LabSem3/Migrations/202206281930539_dbcontext.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
