// <auto-generated />
namespace LabSem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbcontext));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:LabSem3/Migrations/202207061146440_Context.Designer.cs
            get { return "202207061146440_Context"; }
=======
            get { return "202207061257440_dbcontext"; }
>>>>>>> bdda67790a8d8771fdb7feaeb855338ac9d7000f:LabSem3/Migrations/202207061257440_dbcontext.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
