// <auto-generated />
namespace LabSem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class abcc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abcc));
        
        string IMigrationMetadata.Id
        {
            get { return "202206231623457_abcc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
