// <auto-generated />
namespace LabSem3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
<<<<<<< HEAD:LabSem3/Migrations/202206221643533_dbcontext.Designer.cs
    public sealed partial class dbcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "202206221643533_dbcontext"; }
=======
    public sealed partial class initDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202206221553505_initDb"; }
>>>>>>> 7839df7ac8596271075dcb750366ebe9138c28ef:LabSem3/Migrations/202206221553505_initDb.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
